#!/bin/bash
#====================================================
# SCRIPT: ELH SERVER QUICK DEPLOY V 1
# DEVELOPED BY: netbro201031
# UPDATE DATE: 2021.10.20
# TELEGRAM CONTACT: HTTPS://T.ME/ELH_NETWOXCLOUD_LIVE_USER 
# THIS REPO SPECIALLY MADE FOR ELH.NETWOXCLOUD SERVERS.
#====================================================

# Update System
sudo apt update 
# Upgrade System
sudo apt upgrade -y
# Install Firewalld
sudo apt-get install firewalld -y
# Open Ports
sudo firewall-cmd --zone=public --permanent --add-port=443/tcp
sudo firewall-cmd --zone=public --permanent --add-port=80/tcp
sudo firewall-cmd --zone=public --permanent --add-port=8080/tcp
sudo firewall-cmd --zone=public --permanent --add-port=7300/tcp
sudo firewall-cmd --zone=public --permanent --add-port=22/tcp
sudo firewall-cmd --zone=public --permanent --add-port=110/tcp
sudo firewall-cmd --zone=public --permanent --add-port=54321/tcp
sudo firewall-cmd --zone=public --permanent --add-port=9090/tcp
sudo firewall-cmd --zone=public --permanent --add-port=10000/tcp
# Reload Firewalld
sudo firewall-cmd --reload
# Adding Cron Job for Start Firewalld
(crontab -l && echo "@reboot systemctl start firewalld") | crontab -
# Install Speedtest CLI
sudo apt install speedtest-cli
# Install Cockpit
sudo apt-get install cockpit -y
# Setup Time Zone
sudo timedatectl set-timezone Asia/Colombo
# Setup Automatic Reboot @ Every day 5 a.m.
(crontab -l && echo "0 5 * * * /sbin/reboot") | crontab -
# Remove Junk Files
sudo apt autoremove -y
# Automate Removing Junk Files 
sudo sh -c 'echo "sudo apt autoremove -y" >> /etc/cron.monthly/autoremove'
# Setup Monthly Junk Remover Job
sudo chmod +x /etc/cron.monthly/autoremove
# System Update to install webmin
sudo apt update
#Install Webmin
sudo apt install wget apt-transport-https software-properties-common -y
wget -q http://www.webmin.com/jcameron-key.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] http://download.webmin.com/download/repository sarge contrib"
sudo apt install webmin -y
# Done
clear
echo "Type Your Web Panal Password"
# Add User 
adduser opcroot
sleep 10s
# Grant Superuser Privileges to Newly added User
usermod -aG sudo opcroot
clear
echo "OPC MAKE FINISHED !"
# Remove opcmake file
rm -r opcmake
